name: install Python packages
description: |
  Install the common Python packages shared by all jobs.
runs:
  using: composite
  steps:
    - name: install Python
      uses: actions/setup-python@v4
      with:
        # The `imp` module is removed in Python 3.12
        # but required by Conan 1.x.
        python-version: '3.11'
    - name: install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: install Conan
      shell: bash
      run: pip install wheel 'conan<2'
    - name: configure Conan
      shell: bash
      run: |
        conan profile new default --detect
        conan profile update settings.compiler.cppstd=20 default
    - name: configure Conan for GCC
      if: runner.os == 'Linux'
      shell: bash
      run: |
        conan profile update settings.compiler.libcxx=libstdc++11 default
