name: test in Unix environment
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu
          - macos
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install environment
        uses: ./.github/actions/install-nix
      - name: add Redirectory
        run: |
          conan remote add redirectory https://conan.jfreeman.dev
          # TODO: Possible to authenticate with ${GITHUB_TOKEN}?
      - name: export Conan packages from template-project-cpp
        run: |
          # They all depend on `cupcake`.
          conan export submodules/project-template-cpp/cupcake
          # `ten` (`10-conan`) depends on `zero`.
          conan export submodules/project-template-cpp/00-upstream
      - name: install dependencies
        run: |
          poetry install
      - name: test project
        run: |
          poetry run pytest -n auto
